accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name = 'login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name = 'logout'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

import accounts
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home_view, name='home'),
    path('admin/', admin.site.urls),
    path('post/',include('post.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name = 'index'),
    path('create/', post_create, name = 'create'),
    path('<slug:slug>/detail/', post_detail, name='detail'),
    path('<slug:slug>/update/', post_update, name = 'update'),
    path('<slug:slug>/delete/', post_delete, name = 'delete'),
    path("search/", search_posts, name = "search"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

def home_view(request):
    if request.user.is_authenticated:
        context = {
            'isim' : request.user.get_full_name(),
        }
    else:
        context = {
            'isim' : 'misafir',
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Kadirin Bloğu {% endblock %} </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet"  href=" {% static 'css/borders.css' %}">
</head>
<body>

{% include 'header.html' %}

{% include 'messages.html' %}

{% block body %}

{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-default navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">
            <!-- Telefon ekranları için menü butonu -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Kadirin Bloğu</a>
        </div>

        <!-- Menü (Düzgün çalışması için ID ekledim) -->
        <div class="collapse navbar-collapse" id="navbar-menu">
            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'post:search' %}">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Ara</button>
                    </span>
                </div>
            </form>

            <!-- Sayfa Linkleri -->
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Yazı Ekle</a></li>
                {% endif %}
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
                {% if not request.user.is_authenticated %}
                <li><a href="{% url 'accounts:login' %}">Giriş Yap</a></li>
                <li><a href="{% url 'accounts:register' %}">Üye Ol</a></li>
                {% else %}
                <li><a href="{% url 'accounts:logout' %}">Çıkış</a></li>
                {% endif %}


            </ul>
        </div>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %} Anasayfa {% endblock %}

{% block body %}

Merhaba, {{ isim }}

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
                {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/search_results.html
{% extends 'base.html' %}  <!-- Ana şablonunu kullanıyorsan ekle -->

{% block body %}
    <h2>Arama Sonuçları: "{{ query }}"</h2>

    {% if results %}
        <ul>
            {% for post in results %}
                <li><a href="{{ post.get_absolute_url }}" >{{ post.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Sonuç bulunamadı.</p>
    {% endif %}
{% endblock %}